version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/db:/var/lib/postgresql/scripts

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code/app/
    depends_on:
      - db

volumes:
  db-data:
